### PR TITLE
docs: document typewiz.json and monorepo

### PR DESCRIPTION
**Pull request by zoehneto**
Part of #31 

Note:
* This PR should probably only be merged shortly before releasing the next version to avoid confusing users looking at the README while config support is not yet available.

### CODE REVIEW

**Comment by urish** [comment]
Thanks! I just published `1.0.0-alpha.0` with the latest changes, and they can be tested by installing `typewiz-node@next`, etc.

I plan to cut 1.0.0 as soon as we get the CLI ready (it's almost there - #60) as well as some automated test on a large code base (just to make sure our instrumentation doesn't product invalid TS code). I hope to get a beta release out this weekend.

**Comment by zoehneto** [comment]
Great. I'll create a PR for Schema Store tomorrow. If you want I can also update the docs for the new monorepo layout.

**Comment by urish** [comment]
Yes please, that would be lovely :)

I just used `lerna publish` for the first time - it's so much more fun that releasing manually :heart_eyes:

**Comment by urish** [comment]
Great! Seems like there's a good chance CLI merge will happen today :)

**Pull request merged**
