### PR TITLE
Angular support

### PR DESCRIPTION
**Pull request by urish**

### CODE REVIEW

**Comment by FallenRiteMonk** [comment]
Whats the state of this PR?

**Comment by urish** [comment]
It was pretty functional, though it had some issue when I used it for an Angular project created with yarn. 

If you are interested, I can write for you instructions how to test it in your project (before it's published to NPM), so you can share your feedback as well

**Comment by FallenRiteMonk** [comment]
@urish that would be great! Thanks

**Comment by tw3** [comment]
> It was pretty functional, though it had some issue when I used it for an Angular project created with yarn.
> 
> If you are interested, I can write for you instructions how to test it in your project (before it's published to NPM), so you can share your feedback as well

Hey @urish I would definitely be interested in learning how to use this tool for an Angular 5 codebase, any tips?

**Comment by urish** [comment]
@tw3 @FallenRiteMonk I published the beta version to npm, so testing should now be pretty much straight forward:

https://medium.com/@urish/angular-schematics-and-the-future-of-typewiz-c266a5442c82

**Comment by FallenRiteMonk** [comment]
@urish Just tried it on a small project of mine and got following error:
```
ERROR in : TypeError: Cannot read property 'text' of undefined
```

Further in the error stack trace I found multiple lines similar to this one:
```
Error: <PATH_TO_PROJECT>/apps/fortysix/src/app/components/features/features.component.ts is missing from the TypeScript compilation.
```

This is in a Nx workspace. Do you want me to give you more info's here, or should I open a new issue?

**Comment by urish** [comment]
@FallenRiteMonk yes, a new issue please. Can you please check if commenting out some of the code in features.component.ts fixes this `TypeError`?

**Pull request merged**
